usethis::use_package("magrittr")
usethis::use_package("tibble")
usethis::use_package("dplyr")
# usethis::use_package("tidyverse",type="Depends")
usethis::use_package("base")
usethis::use_package("purrr")
usethis::use_package("tidyr")
usethis::use_package("gt")
usethis::use_pkgdown()
# devtools::use_vignette("CheckOfTable",pkg="CheckOfTable")
# usethis::use_vignette("CheckOfTable")
# repo_url <- "https://github.com/SebastienBoutry/CheckOfTable"
# usethis::use_git_remote(url = repo_url)
